#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HarmonyApp.Resource", IsApplication=true)]

namespace HarmonyApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edwin_andrade_158050_e1502792382504 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int imageedit_2_3489386837_e1514762315785_c = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int buttonExternalSermonAccess = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int buttonLaunchEventCalendar = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int buttonLaunchResonate = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int calendarView1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int gridLayout1 = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int imageViewLogo = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayoutH_TitleBar = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int linearLayoutV1 = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int relativeLayout1 = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int spinnerResonateSermonSelect = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int textChurchSummary = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textViewAlternateResonateMethod = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int textViewEventCalendar = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int textViewResonate = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventCalendar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Resonate = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
